env: "local"

http_server:
  port: "8080"
  timeout: 5s

postgres:
  host: "db"
  port: "5432"
  user: "postgres"
  dbname: "postgres"
  password: "pass"
  timeout: 60s

kafka:
  replication_factor: 1
  brokers:
    - host: "kafka-1"
      port: "9092"
